### PR TITLE
no semicolons

### PR DESCRIPTION
**Pull request by HudsonHurtig**
this has no semicolons

### CODE REVIEW

**Review by gtjones02 — CHANGES_REQUESTED** [review]
semicolons are good

**Review by gtjones02 — CHANGES_REQUESTED** [review]
semicolons are good

**Review by TheChar — CHANGES_REQUESTED** [review]
Wanting the semicolons back very badly

**Review by Team1710CTO — CHANGES_REQUESTED** [review]
No, bad. We like ;

**Review by rahidas04 — COMMENTED** [review]
Need to add in Semicolons

**Pull request closed without merging**
